// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCY9XTK8-2SmULRCDI8ZgItD3rHzgguOzE',
    appId: '1:28499378507:web:87178ff078ce2557b568ce',
    messagingSenderId: '28499378507',
    projectId: 'flutter-pizza-8450a',
    authDomain: 'flutter-pizza-8450a.firebaseapp.com',
    storageBucket: 'flutter-pizza-8450a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxh_HNf9UWKOEAqFlf98cD3NiCqGQ4qng',
    appId: '1:28499378507:android:a2ffa7a546ffca0cb568ce',
    messagingSenderId: '28499378507',
    projectId: 'flutter-pizza-8450a',
    storageBucket: 'flutter-pizza-8450a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxZzCHQLPQHcLtN7gU-LN7gf_RcfDuzKQ',
    appId: '1:28499378507:ios:da92bc69daf39f24b568ce',
    messagingSenderId: '28499378507',
    projectId: 'flutter-pizza-8450a',
    storageBucket: 'flutter-pizza-8450a.appspot.com',
    iosBundleId: 'com.example.utsApp',
  );
}
